---
# tasks file for Windows_Implementation

- name: Manage Environmental Variable
  win_path:
    name: "{{ env_var }}"
    elements: "{{ path }}"
    scope: "{{ scope }}"
    state: "{{ env_state }}"
  tags:
    - env_variable


- name: Execute command
  win_shell: "{{ item }}"
  register: command_output
  with_items: "{{ commands }}"
  tags:
    - execute_cmd


- name: Set timezone
  win_timezone:
    timezone: "{{ standard_time_zone }}"
  tags:
    - timezone

- debug:
    msg: "Server restart is needed"


- name: Making entry in host
  win_lineinfile:
    path: "{{ host_path }}"
    line: "{{ line_to_be_insert }}"
    state: "{{ state }}"
  tags:
    - hostfile

- debug:
    msg: "Server restart is needed"

    
    
