env_var:
path:
scope:
env_state:

commands: 

standard_time_zone:

host_path: C:\Windows\System32\Drivers\etc\hosts
line_to_be_insert:
state:

unitNumber:
page_size:

File_Path_To_be_saved: C:/Users/Administrator/Desktop/Reports/Service_Status_Report.csv
