---
# vars file for Windows_Implementation

env_var: CLASSPATH                                 # Target path environment variable name
path: C:\Program Files\MyJavaThing                 # A single path element, or a list of path elements to add or remove
scope: user                                        # The level at which the environment variable specified should be managed
env_state: absent                                  # Whether the path elements specified in elements should be present or absent


commands:                                          # Enter commands to be executed
    - echo %HOMEDIR%
    - echo %DIRECTORY%

standard_time_zone: Central Standard Time          # Timezone to set to

host_path: C:\Windows\System32\Drivers\etc\hosts   # The path of the file to be modified
line_to_be_insert: 'name=Test'                     # The line to insert/replace into the file
state: present                                     # Whether the line should be there or not
